FROM node:18.4.0 as frontend_builder
WORKDIR /app

COPY starcev-front/package.json .
COPY starcev-front/package-lock.json .

RUN npm install
COPY ./starcev-front .
RUN npm run build



FROM python
WORKDIR /app
COPY ./backend/requiments.txt .
RUN pip install -r requiments.txt
RUN pip install gunicorn

ENV PORT 3000

EXPOSE $PORT
COPY ./backend .
COPY --from=frontend_builder /app/dist/ app/app/static

# CMD ["flask", "run", "--host=0.0.0.0", "--debug"]
CMD ["gunicorn", "-w", "2", "-b", "0.0.0.0:3000", "app:create_app()"]